In [2]:
import numpy as np

1:-

Write a Numpy program to get the Numpy version and show the Numpy build configuration.

In [18]:
print(np.__version__)


1.23.5


In [19]:
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/madhu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/madhu/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/madhu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/madhu/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/madhu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/madhu/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/madhu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/madhu/anaconda3\\Lib

2. Write a NumPy program to get help with the add function.

In [21]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [23]:
np.add(5,8)

13

In [39]:
x1=np.arange(8.0).reshape((2,4))
x2=np.arange(4.0)


np.add(x1,x2)
#x1+x2

array([[ 0.,  2.,  4.,  6.],
       [ 4.,  6.,  8., 10.]])

In [35]:
x2

array([0., 1., 2.])

In [36]:
x1

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

3. Write a NumPy program to test whether none of the elements of a given array are zero.

In [43]:
x=np.array([1,2,3,4,5])
print("Test if none of the element of said array is zero :")
print(x)
np.all(x)

Test if none of the element of said array is zero :
[1 2 3 4 5]


True

In [44]:
x=np.array([0,1,2,3,])
print('Test if none of the element of said array is zero:')
np.all(x)

Test if none of the element of said array is zero:


False

4. Write a NumPy program to test if any of the elements of a given array are non-zero

In [47]:
x=np.array([1,0,0,0])

print("Test if any of the elements of a given aray are non-zero:")
print(np.any(x))

Test if any of the elements of a given aray are non-zero:
True


5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [51]:
x=np.array([1,2,np.nan,np.inf])
print("Test the given array element-wise for finitness:")
print(np.isfinite(x))

Test the given array element-wise for finitness:
[ True  True False False]


In [49]:
np.nan

nan

6. Write a NumPy program to test elements-wise for positive or negative infinity. 

In [53]:
x=np.array([1,2,np.nan,np.inf])
print('Test to element-wise for positive or negative infinity:')
print(np.isinf(x))

Test to element-wise for positive or negative infinity:
[False False False  True]


7. Write a NumPy program to test element-wise for NaN of a given array.

In [54]:
x=np.array([1,2,3,np.nan,np.inf])
print("Test element-wise foro nan of a given array:")
print(np.isnan(x))

Test element-wise foro nan of a given array:
[False False False  True False]


8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not

In [4]:
x=np.array([1,2,1+2j,3,2j,5])
print("Check complex number:")
print(np.iscomplex(x))

Check complex number:
[False False  True False  True False]


In [5]:
print("Check real number :")
print(np.isreal(x))

Check real number :
[ True  True False  True False  True]


In [8]:
print(np.isscalar([3.0]))

False


In [9]:
print(np.isscalar(3.0))

True


9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [16]:
x=np.array([1,4,3])
y=np.array([5,3,6])
print("Original array :")
print(x)
print(y)

print("Comparison greater  :")
print(np.greater(x,y))

Original array :
[1 4 3]
[5 3 6]
Comparison greater  :
[False  True False]


In [17]:
print("comparison greater_equal:")
print(np.greater_equal(x,y))

comparison greater_equal:
[False  True False]


In [18]:
print("comparison less:")
print(np.less(x,y))

comparison less:
[ True False  True]


In [19]:
print("comparison less_equal:")
print(np.less_equal(x,y))

comparison less_equal:
[ True False  True]


11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [20]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("original numbers :")
print(x)
print(y)
print("equal comparison :")
print(np.equal(x,y))
print("equal within tolerance comparison :")
print(np.allclose(x,y))


original numbers :
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
equal comparison :
[ True  True  True  True  True  True  True  True  True False]
equal within tolerance comparison :
True


12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [22]:
x=np.array([1,7,13,105])
print("original array:")
print(x)
print("The size of the memory occupied by the said array :")
print("%d bytes" % (x.size * x.itemsize))

original array:
[  1   7  13 105]
The size of the memory occupied by the said array :
16 bytes


13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [24]:
print("Array of 10 zeros :")
print(np.zeros(10))

Array of 10 zeros :
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
print("Array of 10 ones :")
print(np.ones(10))

Array of 10 ones :
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [32]:

x=np.zeros(10)
print(x)
y=np.add(x,5)
print("Array of 10 fives :")

print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 fives :
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [29]:
x = np.arange(10).reshape((2,5))
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [30]:
np.add(x,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
print("array of 10 fives :")
print((np.ones(10)*5))

array of 10 fives :
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


14. Write a NumPy program to create an array of integers from 30 to 70.

In [35]:
print("Array of integers from 30 to 70 :")
print(np.arange(30,70))

Array of integers from 30 to 70 :
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


15.Write a NumPy program to create an array of all even integers from 30 to 70.

In [39]:
x=np.arange(30,71,2)
print((x))


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


16. Write a NumPy program to create a 3x3 identity matrix.

In [40]:
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
print("3x3 matrix is :")
x=np.identity(3)
print(x)

3x3 matrix is :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17. Write a NumPy program to generate a random number between 0 and 1.

In [44]:
print("Random number between 0-1 :")
print(np.random.randint(0,1))

Random number between 0-1 :
0


In [46]:
np.random.randint(1,10,)

array([8, 8])

In [53]:
print("Random number between 0-1 :")
print(np.random.normal(0,1,1))

Random number between 0-1 :
[0.5374365]


18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [75]:
x=np.random.normal(0,1,15).reshape((3,5))

In [77]:
print(x)

[[ 0.27086359  1.03786009 -0.99094489 -0.98861135  1.61365334]
 [ 0.02691532  2.03921044  0.01695249 -0.85419949  0.15476548]
 [ 0.7551914  -0.70774334  0.57593339  0.21386795 -0.12776064]]


19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [78]:
v=np.arange(15,55)
print("original value of vector :")
print(v)
print("all values excepting 1st and last :")
print(v[1:-1])

original value of vector :
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
all values excepting 1st and last :
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [90]:
x=np.arange(32).reshape(2,2,2,2,2)
print(x)

[[[[[ 0  1]
    [ 2  3]]

   [[ 4  5]
    [ 6  7]]]


  [[[ 8  9]
    [10 11]]

   [[12 13]
    [14 15]]]]



 [[[[16 17]
    [18 19]]

   [[20 21]
    [22 23]]]


  [[[24 25]
    [26 27]]

   [[28 29]
    [30 31]]]]]


In [91]:
type(x)

numpy.ndarray

20. Write a NumPy program to create a 3X4 array and iterate over it.

In [114]:

x=np.arange(10,22).reshape((3,4))
print("original array")
print(x)
print("Elements of the array :")
for i in np.nditer(x):
    print(x,end="")

original array
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Elements of the array :
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]][[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

In [112]:
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
    print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [127]:
x=np.linspace(5,50,10)

In [128]:
print(x)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [129]:
x=np.linspace(10,50,5)
print(x)

[10. 20. 30. 40. 50.]


In [130]:
len(x)

5

22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [133]:
x=np.arange(21)
print("Original array :")
print(x)
print("Affter changing sign : ")
x[(x>=9) &(x<=15)] *= -1
print(x)

Original array ;
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Affter changing sign : 
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [134]:
x=np.random.randint(0,11,5)
print(x)

[10  8  8 10  5]
