# Numpy array

In [1]:
import numpy as np

In [3]:
lst=[1,2,3,4]
arr=np.array(lst)


In [4]:
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4])

In [6]:
arr.shape


(4,)

In [7]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [8]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr1.shape

(3, 5)

In [11]:
arr[2]

3

In [13]:
arr[3]=5

In [14]:
arr

array([1, 2, 3, 5])

In [15]:
arr[-1]

5

In [16]:
arr[::-3]

array([5, 1])

In [17]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [18]:
arr1[:,1]

array([2, 3, 4])

In [19]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [21]:
arr1[:-1,3:]

array([[4, 5],
       [5, 6]])

In [22]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [23]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [25]:
arr1[:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [28]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [30]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.random.randint(1,10,6).reshape(2,3)

array([[7, 5, 6],
       [2, 1, 8]])

In [35]:
np.random.randn(3,5)

array([[ 1.04119475, -1.0460504 , -0.49958097, -0.86513007,  0.83058204],
       [-0.5038416 , -0.86982755, -0.81077755, -1.29891499, -0.52861591],
       [ 0.14812735,  1.5580559 , -0.19038815, -0.27430031, -1.29411817]])

In [36]:
arr

array([1, 2, 3, 5])

In [42]:
arr<2

array([ True, False, False, False])

In [43]:
arr[arr<3]

array([1, 2])

In [41]:
np.random.random_sample((4,5))

array([[0.7036376 , 0.21351645, 0.88909687, 0.79267866, 0.54812716],
       [0.7061204 , 0.37436589, 0.97498225, 0.24735015, 0.54242927],
       [0.138496  , 0.88660018, 0.26129613, 0.23492581, 0.49439603],
       [0.50622297, 0.48456816, 0.61169872, 0.2060466 , 0.47565115]])

In [46]:
arr.reshape(2,2) #2 dimensional

array([[1, 2],
       [3, 5]])

In [49]:
arr.reshape(2,2,1) #3 dimensional

array([[[1],
        [2]],

       [[3],
        [5]]])