In [1]:
import pandas as pd


In [2]:
data={
    'Name':['Debu','Bubu','Ranjit'],
    'Age':[19,20,25]
}
df=pd.DataFrame(data)
df

Name  Age
0    Debu   19
1    Bubu   20
2  Ranjit   25

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
l=LabelEncoder()
d=df.columns
for i in d:
    if df[i].dtypes=='object':
        df[i]=l.fit_transform(df[i])

In [5]:
df

Name  Age
0     1   19
1     0   20
2     2   25

In [6]:
data1={
    'Name':['Debu','Bubu','Gudu','Ranjit'],
    'Age':[19,20,23,26],
    'city':['Delhi','Mumbai','Pune','Bengaluru'],
    'ID':[101,102,302,283]
}
df=pd.DataFrame(data1)
df

Name  Age       city   ID
0    Debu   19      Delhi  101
1    Bubu   20     Mumbai  102
2    Gudu   23       Pune  302
3  Ranjit   26  Bengaluru  283

In [7]:
l=LabelEncoder()
d=df.columns
for i in d:
    if df[i].dtypes=='object':
        df[i]=l.fit_transform(df[i])
    

In [8]:
df

Name  Age  city   ID
0     1   19     1  101
1     0   20     2  102
2     2   23     3  302
3     3   26     0  283

In [9]:
#LableEncoding without sklearn

class labelEncoder:
    def __init__(self):
        self.label_map={}
        self.reverse_label_map={}
        self.current_label=0
    def fit(self,label):
        for label in labels:
            if label not in self.label_map:
                self.label_map[label]=self.current_label
                self.reverse_label_map[self.current_label]=label
                self.current_label +=1
    def transform(self,labels):
        encoded_labels=[]
        for label in labels:
            if label in self.label_map:
                encoded_labels.append(self.label_map[label])
            else:
                raise ValueError (f"Label '{label}' not found in label maping")
                                  
        return encoded_labels
                            
    def inverse_transform(self,encoded_labels):
        original_labels=[]
        for encoded_label in encoded_labels:
            if encoded_label in self.reverse_label_map:
                original_labels.append(self.reverse_label_map[encoded_label])
            else:
                raise VallueError (f"encoded label 'encoded_label' not found in reverse label maping")                         
        return original_labels
    
Fruits=['Apple','Orange','Pineapple','cherry','Guava']

#create and fit the label encoder
encoder=LabelEncoder()
encoder.fit(Fruits)

#transform the labels to  encoded integers
encoded_labels=encoder.transform(Fruits)
print("Encoded labels ",encoded_labels)

#invers transform to get back the original labels
decoded_labels=encoder.inverse_transform(encoded_labels)
print("Decoded Labels :",decoded_labels)


                                   
                                   
                                   
                                   
                                   
                                   
                                   
                                  

                                  
                                  

Encoded labels  [0 2 3 4 1]
Decoded Labels : ['Apple' 'Orange' 'Pineapple' 'cherry' 'Guava']


# min-maxscaler

In [10]:
df

Name  Age  city   ID
0     1   19     1  101
1     0   20     2  102
2     2   23     3  302
3     3   26     0  283

In [25]:
from sklearn.preprocessing import MinMaxScaler
data=np.arange(0,20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
scaler=MinMaxScaler()
scaled_data=scaler.fit_transform(data)
print(scaled_data)

[[0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
 [1.         1.         1.         1.         1.        ]]


minmaxsscaler without sklearn library

In [14]:
#min-max scaler for single data
data=[1.0,2.0,3.0,4.0,5.0]
def min_max_scaler(dataset):
    min_val=min(dataset)
    max_val=max(dataset)
    scaled_data=[(x-min_val)/(max_val-min_val) for x in dataset]
    return scaled_data
scaled_data=min_max_scaler(data)
print(scaled_data)

[0.0, 0.25, 0.5, 0.75, 1.0]


In [27]:
#min_max_scaler for multiple element array

def min_max_scaler(dataset,feature_range=(0,1)):
    dataset=np.array(dataset)
    min_val=dataset.min()
    max_val=dataset.max()
    
    if min_val==max_val:
        #Handle the case where all the value are same to avoid division by zero
        return np.full(dataset.shape,feature_range[0])
    scaled_data=(dataset-min_val)/(max_val-min_val)*(feature_range[1]-feature_range[0])+feature_range[0]
    
    return scaled_data
data=np.arange(0,20).reshape(4,5)
scaled_data=min_max_scaler(data,feature_range=(0,1))
print(scaled_data)

[[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]
 [0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]]
