In [1]:
import numpy as np


In [3]:
#1
np.__version__

'1.23.5'

2. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

In [4]:
lst=[1,2,3,4,5]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5])

3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [6]:
arr=np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

In [7]:
arr=np.zeros(10)

In [8]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
arr[6]=11

In [10]:
arr

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

5. Write a NumPy program to create an array with values ranging from 12 to 38.


In [11]:
arr=np.arange(12,39).reshape(3,9)
arr

array([[12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38]])

In [12]:
#make it reverse of 2 dimension

arr[::-1]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [13]:
lst=[1,2,4,6,7]
arr=np.array(lst)

In [14]:
arr

array([1, 2, 4, 6, 7])

In [17]:
arr[::-1]

array([7, 6, 4, 2, 1])

7-Write a NumPy program to convert an array to a floating type.

In [21]:
np.asfarray(arr)

array([1., 2., 4., 6., 7.])

8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [27]:
arr=np.ones(25).reshape(5,5)
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
arr[1:4,1:4]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [29]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  9,  0],
       [ 0, 10, 11, 12, 13, 14,  0],
       [ 0, 15, 16, 17, 18, 19,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

10. Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

In [33]:
import numpy as np

print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


11. Write a NumPy program to convert a list and tuple into arrays.


In [40]:
lst=[1,2,3,4,5,6]
tpl=([5,6,7],[8,9,7])
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5, 6])

In [41]:
np.array(tpl)

array([[5, 6, 7],
       [8, 9, 7]])

12. Write a NumPy program to append values to the end of an array.


In [44]:
arr1=[1,2,3,4]
print("Original array :")
print(arr1)
arr=np.append(arr1,[[5,6,7],[8,9,10]])
print("After append array :")
print(arr)

Original array :
[1, 2, 3, 4]
After append array :
[ 1  2  3  4  5  6  7  8  9 10]


13. Write a NumPy program to create an empty and full array.


In [51]:
np.empty(7)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.71349263e-312])

In [50]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

14. Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees.

15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.


In [54]:
#x=np.array([1+0j])
#y=np.array([0+1j])
x=np.sqrt([1+0j])
y=np.sqrt([0+1j])
print("Original arrays :")
print(x)
print(y)
print("'x' array real :",x.real)
print("'y' array real :",y.real)
print("'x' array imaginary :",x.imag)
print("'y' array imaginary :",y.imag)


Original arrays :
[1.+0.j]
[0.70710678+0.70710678j]
'x' array real : [1.]
'y' array real : [0.70710678]
'x' array imaginary : [0.]
'y' array imaginary : [0.70710678]


16. Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.


In [57]:
arr=np.array([1,2,3],dtype=np.float64)
print("The number of elements in arr :",arr.size)
print("The length of one element in bytes :",arr.itemsize)
print("The totsl bytes consumed by the elements :",arr.nbytes)

The number of elements in arr : 3
The length of one element in bytes : 8
The totsl bytes consumed by the elements : 24
