24. Write a NumPy program to multiply the values of two given vectors.

In [1]:
import numpy as np

x=np.array([1,2,3,4])
print("original vector-1:")
print(x)
y=np.random.randint(0,10,4)
print("original vector-2:")
print(y)
print("Multiplication of two vector :")
print(x*y)

original vector-1:
[1 2 3 4]
original vector-2:
[3 6 5 5]
Multiplication of two vector :
[ 3 12 15 20]


25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [2]:
x=np.arange(10,22).reshape(3,4)
print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


26. Write a NumPy program to find the number of rows and columns in a given matrix.

In [5]:
x=np.arange(1,10).reshape(3,3)
print(x)
print("rows and culumn are :")
print(x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
rows and culumn are :
(3, 3)


27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

In [9]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [16]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [19]:
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

# pandas

In [20]:
import numpy as np
import pandas as pd


In [51]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","row5"],columns=["column1","column2","column3","column4"])
print(df)

      column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
row5       16       17       18       19


In [23]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
row5       16       17       18       19

In [24]:
df.tail()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
row5       16       17       18       19

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [26]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [99]:
df.shape

(3, 3)

In [101]:
df.dtypes

a    int64
b    int64
c    int64
dtype: object

In [27]:
#indexing#column indexing

df[["column1","column2","column3",]]

column1  column2  column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
row5       16       17       18

In [31]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [33]:
df["column1"]

Row1     0
Row2     4
Row3     8
Row4    12
row5    16
Name: column1, dtype: int32

In [34]:
#Row indexing
df.loc["Row1"]

column1    0
column2    1
column3    2
column4    3
Name: Row1, dtype: int32

In [35]:
df.loc[["Row1","Row2","Row3"]]

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11

In [36]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
row5       16       17       18       19

In [37]:
df.iloc[2:4,0:2]

column1  column2
Row3        8        9
Row4       12       13

In [40]:
df.iloc[1:3,1:2]

column2
Row2        5
Row3        9

In [41]:
#convert dataframe into arrays
df.head().values


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1","Row2"],columns=["column1","column2","column3"])
print(df)

      column1  column2  column3
Row1        1      NaN        2
Row2        1      3.0        4


In [45]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [47]:
df.isnull()

column1  column2  column3
Row1    False     True    False
Row2    False    False    False

In [50]:
df["column3"].value_counts()

2    1
4    1
Name: column3, dtype: int64

In [52]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","row5"],columns=["column1","column2","column3","column4"])
print(df)

      column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
row5       16       17       18       19


In [54]:
df["column2"].unique()

array([ 1,  5,  9, 13, 17])

In [57]:
df[df["column1"]>5]


column1  column2  column3  column4
Row3        8        9       10       11
Row4       12       13       14       15
row5       16       17       18       19

# 1.StringIO


# 2.pandas read_csv

In [58]:
from io import StringIO


In [61]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/RanjitM007/DATASETS/main/ADANI%20PORTS%20AND%20SPECIAL%20ECONOMIC%20ZONE%20LTD.csv')
df.head()

Security Code Type                                Issuer Name Security Id  \
0       532921.0  BSE  Adani Ports and Special Economic Zone Ltd  ADANIPORTS   
1       532921.0  BSE  Adani Ports and Special Economic Zone Ltd  ADANIPORTS   
2       532921.0  BSE  Adani Ports and Special Economic Zone Ltd  ADANIPORTS   
3       532921.0  BSE  Adani Ports and Special Economic Zone Ltd  ADANIPORTS   
4       532921.0  BSE  Adani Ports and Special Economic Zone Ltd  ADANIPORTS   

                                Security Name  Status Group  Face Value  \
0  ADANI PORTS AND SPECIAL ECONOMIC ZONE LTD.  Active    A          2.0   
1  ADANI PORTS AND SPECIAL ECONOMIC ZONE LTD.  Active    A          2.0   
2  ADANI PORTS AND SPECIAL ECONOMIC ZONE LTD.  Active    A          2.0   
3  ADANI PORTS AND SPECIAL ECONOMIC ZONE LTD.  Active    A          2.0   
4  ADANI PORTS AND SPECIAL ECONOMIC ZONE LTD.  Active    A          2.0   

        ISIN No              Industry  ... Industry New Name  \
0  INE742F01042  Port & Port services  ...          Services   
1  INE742F01042  Port & Port services  ...          Services   
2  INE742F01042  Port & Port services  ...          Services   
3  INE742F01042  Port & Port services  ...          Services   
4  INE742F01042  Port & Port services  ...          Services   

                Igroup Name        ISubgroup Name Date Open High  Low  Close  \
0  Transport Infrastructure  Port & Port services  NaN  NaN  NaN  NaN    NaN   
1  Transport Infrastructure  Port & Port services  NaN  NaN  NaN  NaN    NaN   
2  Transport Infrastructure  Port & Port services  NaN  NaN  NaN  NaN    NaN   
3  Transport Infrastructure  Port & Port services  NaN  NaN  NaN  NaN    NaN   
4  Transport Infrastructure  Port & Port services  NaN  NaN  NaN  NaN    NaN   

   Adj Close  Volume  
0        NaN     NaN  
1        NaN     NaN  
2        NaN     NaN  
3        NaN     NaN  
4        NaN     NaN  

[5 rows x 22 columns]

In [80]:
data=('col1,col2,col3\n'
      'x,y,1\n'
      'c,d,2')

In [81]:
StringIO(data)

In [82]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    c    d     2

In [84]:
pd.read_csv(StringIO(data),usecols=['col1','col2'])

col1 col2
0    x    y
1    c    d

In [85]:
df.to_csv('test.csv')

In [86]:
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11')

In [88]:
df=pd.read_csv(StringIO(data))
df

a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [89]:
df.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [91]:
df=pd.read_csv(StringIO(data),dtype={"a":int,"b":float,"c":int})

In [93]:
df.info


<bound method DataFrame.info of    a     b   c    d
0  1   2.0   3  4.0
1  5   6.0   7  8.0
2  9  10.0  11  NaN>

In [94]:
df.dtypes

a      int32
b    float64
c      int32
d    float64
dtype: object

In [95]:
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11')

In [98]:
df=pd.read_csv(StringIO(data),usecols=['a','b','c'],index_col=False)
df

a   b   c
0  1   2   3
1  5   6   7
2  9  10  11

In [103]:
for d in df.c:
    print(d)

3
7
11


In [106]:
ls=df.c.to_list()

In [107]:
ls

[3, 7, 11]

In [109]:
ls=sorted(ls)
df['d']=ls
df.head()

a   b   c   d
0  1   2   3   3
1  5   6   7   7
2  9  10  11  11

### ABS
    - absolute difference between two pandas DataFrame columns